a = int(input("Digite o primeiro valor: "))
b = int(input("Digite o segundo valor: "))
soma = a + b
subtracao = a - b
multiplicacao = a * b
divisao = a / b
resto = a % b
resultado = print(f"Soma: {soma}, Subtracao: {subtracao}, Multiplicacao: {multiplicacao}, Divisao: {divisao}, Resto: {resto}")
print = str(resultado)